config/routes.rb
Selftaught::Application.routes.draw do
  resources :taughts

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

end

app/models/taught.rb
class Taught < ActiveRecord::Base
  attr_accessible :description, :name, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation
  
  has_many :taughts


  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	before_filter :login_required, :only => [:home]
	
	
	def index
		if logged_in?
			redirect_to :action => 'home'
		end
	end
	
	
	def home
	
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to_target_or_default root_url, :notice => "Logged in successfully."
    else
      flash.now[:alert] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You have been logged out."
  end
end

app/controllers/taughts_controller.rb
class TaughtsController < ApplicationController
  # GET /taughts
  # GET /taughts.json
  def index
    @taughts = Taught.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @taughts }
    end
  end

  # GET /taughts/1
  # GET /taughts/1.json
  def show
    @taught = Taught.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @taught }
    end
  end

  # GET /taughts/new
  # GET /taughts/new.json
  def new
    @taught = Taught.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @taught }
    end
  end

  # GET /taughts/1/edit
  def edit
    @taught = Taught.find(params[:id])
  end

  # POST /taughts
  # POST /taughts.json
  def create
    @taught = Taught.new(params[:taught])

    respond_to do |format|
      if @taught.save
        format.html { redirect_to @taught, notice: 'Taught was successfully created.' }
        format.json { render json: @taught, status: :created, location: @taught }
      else
        format.html { render action: "new" }
        format.json { render json: @taught.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /taughts/1
  # PUT /taughts/1.json
  def update
    @taught = Taught.find(params[:id])

    respond_to do |format|
      if @taught.update_attributes(params[:taught])
        format.html { redirect_to @taught, notice: 'Taught was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @taught.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taughts/1
  # DELETE /taughts/1.json
  def destroy
    @taught = Taught.find(params[:id])
    @taught.destroy

    respond_to do |format|
      format.html { redirect_to taughts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Thank you for signing up! You are now logged in."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Your profile has been updated."
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/taughts_helper.rb
module TaughtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
	<%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tag %>
	<%= yield(:head) %>
</head>
	<body>

		<div class="navbar navbar-fixed-top navbar-inverse">
			<div class="navbar-inner">
				<div class="container">
					  <a class="brand" href="#">Self-Taught</a>
					  <ul class="nav">
					 	<li><a href="/home">Home</a></li>
						<% if logged_in? %>
						<li><%= link_to 'My Taughts', taughts_path %></li>
						<li><a href="#">Courses</a></li>	
						<li><a href="#">Friends</a></li>
						<% else %>
						<li><a href="#">About</a></li>
						<% end %>
					  </ul>
					  	<ul class="nav pull-right">
					  	<% if logged_in? %>
					  		<li class="dropdown">
					  		    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
					  		        <%= current_user.username %> <b class="caret"></b>
					  		    </a>
                                <ul class="dropdown-menu">
                                    <li><a href="/user/edit">Update Profile</a></li>
                                    <li><a href="/logout">Logout</a></li>
                                </ul>
					  		</li>
					  		
					  	<% else %>
					  	</ul>
					 
					  	<form action="<%= sessions_path %>" method="post" class="navbar-form pull-right" >
    						<input type="text" name="login" placeholder="Username or Email Address" 								   class="span2"/>
    						<input type="password" name="password" placeholder="Password" class="span2"/>
    						<input type="submit" value="Log in" class="btn btn-primary"/>
						    <a href="/signup" class="btn btn-success">Signup</a>

					  	</form>
					  	<% end %>
					  	
				</div>
			</div>
		</div>


	<div class="hero-unit">
		<div id="container">
			<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, :id => "flash_#{name}" %>
			<% end %>
<!--			<%= content_tag :h1, yield(:title) if show_title? %>-->
			<%= yield %>
		</div>
	</div>
	</body>
</html>

app/views/main/home.html.erb
<% title "Home" %>

<div>
	Testeee
</div>

app/views/main/index.html.erb
<% title "Self-Taught" %>
<div class="well">
	index page
	
</div>

app/views/taughts/_form.html.erb
<%= form_for(@taught) do |f| %>
  <% if @taught.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taught.errors.count, "error") %> prohibited this taught from being saved:</h2>

      <ul>
      <% @taught.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taughts/edit.html.erb
<h1>Editing taught</h1>

<%= render 'form' %>

<%= link_to 'Show', @taught %> |
<%= link_to 'Back', taughts_path %>

app/views/taughts/index.html.erb
<% title "Listing taughts" %>
<h1>Listing taughts</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @taughts.each do |taught| %>
  <tr>
    <td><%= taught.name %></td>
    <td><%= taught.description %></td>
    <td><%= link_to 'Show', taught %></td>
    <td><%= link_to 'Edit', edit_taught_path(taught) %></td>
    <td><%= link_to 'Destroy', taught, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Taught', new_taught_path %>

app/views/taughts/new.html.erb
<h1>New taught</h1>

<%= render 'form' %>

<%= link_to 'Back', taughts_path %>

app/views/taughts/show.html.erb
<% title @taught.name %>
<p>
  <b>Name:</b>
  <%= @taught.name %>
</p>

<p>
  <b>Description:</b>
  <%= @taught.description %>
</p>

<p>
  <b>User:</b>
  <%= link_to @taught.user.username, @taught.user %>
</p>


<%= link_to 'Edit', edit_taught_path(@taught) %> |
<%= link_to 'Back', taughts_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
<% end %>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>